### ISSUE TITLE
Tutorials

### ISSUE THREAD

**Issue by ImmanuelSamuel** [HaxeFoundation/hashlink#136]
Can we have some advanced tutorials? I am able to run basic hl code. But I am not able to find any tutorials for SDL. I am trying to create some windows and show some text. Couldnt get it to work. I then found the uvsample in other but got error ```Failed to load library uv.hdll```.  But I have the file in the hl folder.

Also I do see this https://github.com/HaxeFoundation/hashlink/tree/master/libs/sdl/sdl ... However to a new user this is too much to take in. Also how to get the bytecode is not clear. This is not a complain but just a request. I am here because I am very interested.

**Comment by ncannasse** [comment]
You usually don't use HL directly at the low level. You can use an higher level API that has an HL implementation, such as Heaps which has samples: https://github.com/heapsio/heaps

**Comment by ncannasse** [comment]
Looks at HaxeUI maybe?

**Comment by ImmanuelSamuel** [comment]
Yes that is what I used HaxeUI + Kha.

**Comment by nanjizal** [comment]
HaxeUI is just a component library it's not related to ImmanuelSamuel's specific question in my opinion.

Low level application native graphics does not really seem to be the focus of Heaps and Kha since they target GPU, but I am not sure the argument that they can not and should not be used for these holds water, after all Visual Studio Code is a node application, I can't see that being really ideal native use case ( haxe can be used with electron ).  I think that native graphics often still uses stuff like OpenGL on the graphics card if you look into how say linux does it but the frameworks handle redraw regions etc...  so I am still suspecting you can do it in say Kha.  You just setup some stuff to only render changed areas and see if you can get it to take less processing, and look at ways to minimize scrolling.

I know you can do multi windows in Swing Haxe relatively easily, I provided a simple example many years ago now only available on Cambiata blog, I expect haxe java now can work with newer java graphics libraries.

https://github.com/cambiata/hx_swing_examples/blob/master/src/hxswing/TwoWindowsExample.hx

There are projects in the haxe ecosystem to access ios and android directly these would make use of native controls and thus access to low level native graphics.

I expect your best bet might be to ask on NME gitter about opening two windows, Hugh is likely to provide a pointer but you will need to be technical to get further, for example I found this:

https://groups.google.com/forum/#!topic/haxelang/4jiEX03gRhw

C# has stuff like Cairo that you can use without hardware acceleration so I guess perhaps more suited to applications.
http://www.mono-project.com/docs/gui/drawing/

on Cambiata github he does some music notation in Cario.

I think the issue is that GPU shader graphics is not as tightly coupled to the operating system as native stuff for drawing text in applications, so it's relatively easy to have cross target solutions. In theory you could hook Hashlink up to c++ libraries for native text, but you may need to implement it differently for each platform.  I think though the approach with Shaders that might be workable in Kha is to explore not clearing the screen most of the time and just drawing the parts that have changed, so like many 3d engines you use dirty flags to know which graphics to redraw, but you would have to manage redrawing anything that was below a changed area.

I don't know if my answer is good or bad but I would just experiment with Kha and realize you have to do a lot yourself, so you need to turn the renderframe loop on and off, so add this to the render loop.
```System.removeRenderListener( render );```
and add the loop again when you need to draw over an area.
```System.notifyOnRender( render );```
I am sure the theory is same in Heaps, NME, OpenFL, you can use renderTextures to try to minimize redraws, perhaps layering content so you only need to change one layer and then draw them to screen, many of them have fallback canvas ( Kha you normally compile specifically for Canvas ) that maybe less accelerated and could be run in electron?

But maybe Nicolas has more technical stuff to add now that I have provided my nieve and limited understanding of the wider differences between application and games focused.  Adobe AIR is often used for application development but it uses swf a mix of software and hardware rendering with layers so not really that different from Heaps that also targets it. Essentially the difference between a game and an app is that with games the whole screen is changing all the time so you often redraw everything with an app it maybe more efficient to only redraw what you need and you may want to avoid shaders etc.. and let the operating system work that out for you, but these days the boundaries are no longer solid.  The differences are often down to having apps that don't drain batteries.

I have documented the Electron application publish workflow if it's useful but still reluctant to advise using these node approaches, you can embed Kha canvas within electron, but not tried yet.

https://github.com/nanjizal/nanjizalOnElectron

Hashlink is not mature enough to consider for native interaction say hooking up dll for native text - in my limited opinion, you should definitely look at hxcpp and ask questions on nme gitter and check out some of the nme samples that use native components.

Again really unsure if all this info I have posted is useful or correct but that's for you to decide and research.
