### ISSUE TITLE
Build instructions (on Ubuntu 16.04)

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/hashlink#147]
Using the apt-get from the readme, I get:

```
sudo apt-get install libpng16-dev libturbojpeg-dev libvorbis-dev libopenal-dev libsdl2-dev libmbedtls-dev libuv1-dev
E: Unable to locate package libturbojpeg-dev
```
The package is not `libturbojpeg-dev`, it's called `libjpeg-turbo8-dev`

But joy upon joy, that package's install is missing a symlink, which causes hl build to break with:

```
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-turbojpeg.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a: error adding symbols: Bad value
```

(Same problem and solution is [mentioned here](https://github.com/OpenKinect/libfreenect2/issues/36#issuecomment-354970899).)

It shouldn't pick up the .a file, it should pick up the .so file. The solution is to create the missing symlink:

```
sudo ln -s /usr/lib/x86_64-linux-gnu/libturbojpeg.so.0 /usr/lib/x86_64-linux-gnu/libturbojpeg.so
```
Then hl build completes successfully!

![image](https://user-images.githubusercontent.com/2192439/39980611-0b3deaea-570a-11e8-8247-81ec0cf11694.png)

We could update the readme with the above, or point folks to this issue.

**Comment by andyli** [comment]
As you've found out, the `libjpeg-turbo8-dev` package on Ubuntu 16.04 provides a static library that was not compiled with `-fPIC`, which it should. The problem has been fixed in later version of the package, which was renamed to `libturbojpeg-dev`. The `libturojpeg-dev` package also provides `libturbojpeg.so`.

If you use Ubuntu 18.04, the current instruction is all good. For Ubuntu 16.04, I will try to figure what is the best instruction.

> It shouldn't pick up the .a file, it should pick up the .so file.

I wouldn't say it **should** pick up which one, since there are reasons for choosing either of those. However, it should be possible to use either. It's just the 16.04 package being faulty.

**Comment by ncannasse** [comment]
@jcward yes the instructions could be updated for Ubuntu 16.x, they are valid for Ubuntu 18.x

**Comment by sonygod** [comment]
Welcome to **Ubuntu 18.04** LTS (GNU/Linux 4.15.0-23-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Mon Aug  6 06:31:57 UTC 2018

  System load:  0.02              Processes:           87
  Usage of /:   8.5% of 24.55GB   Users logged in:     0
  Memory usage: 12%               IP address for ens3: 45.32.145.179
  Swap usage:   0%


0 packages can be updated.
0 updates are security updates.


/usr/bin/xauth:  file /root/.Xauthority does not exist
root@vultr:~# mkdir hashlink
root@vultr:~# cd hashlink
root@vultr:~/hashlink# git clone https://github.com/HaxeFoundation/hashlink.git
Cloning into 'hashlink'...
remote: Counting objects: 6660, done.
remote: Compressing objects: 100% (52/52), done.
remote: Total 6660 (delta 24), reused 42 (delta 14), pack-reused 6594
Receiving objects: 100% (6660/6660), 6.09 MiB | 9.27 MiB/s, done.
Resolving deltas: 100% (4475/4475), done.
root@vultr:~/hashlink# sudo apt-get install libpng16-dev libturbojpeg-dev libvorbis-dev libopenal-dev libsdl2-dev libmbedtls-dev libuv1-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libturbojpeg0-dev' instead of 'libturbojpeg-dev'
Package libpng16-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libpng-dev:i386 libpng-dev

**E: Package 'libpng16-dev' has no installation candidate**

**Comment by sonygod** [comment]
Try libpng-dev

**Comment by hsandt** [comment]
So, I built libjpeg-turbo myself from the GitHub repository (I picked version 2.0.0). Building is easy on Linux, you can just follow the instructions at [https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/BUILDING.md](BUILDING.md). The only special requirement is that you need NASM or YASM; I don't know anything about them, so I just installed the first one:

```
sudo apt install nasm
cd {libjpeg-turbo-root}
mkdir build
cd build
cmake -G"Unix Makefiles" ..
make
sudo make install

```

If you look at the CMakeLists.txt, you'll see CMAKE_POSITION_INDEPENDENT_CODE mentioned. Basically, if you set no extra option for cmake you should get position-independent code (-fPIC) which is what we want.

Now just try to `make` hashlink again.

P.S.: I managed to build hashlink this way but couldn't test it due to compatibility issues with haxe (1.7 is too advanced, I need to go back to 1.1 or get a nightly build of haxe). I didn't manage to make that work, so maybe I'll post another issue later.

**Comment by ikoryakovskiy** [comment]
I had exactly same issue on Ubuntu 16.04 but with caffe. A workaround that worked for me:

`sudo apt-get install libturbojpeg`
`sudo ln -s /usr/lib/x86_64-linux-gnu/libturbojpeg.so.0.1.0 /usr/lib/x86_64-linux-gnu/libturbojpeg.so`

If I understand it correctly, the libturbojpeg package is a workaround for the -fPIC, however, for other libraries to pick a new libturbojpeg, the new link has to be created.

**Comment by jingkang99** [comment]
!!!  for libjpeg-turbo and turbovnc, specify -**fPIC** when create make file !!!

cmake -G "Unix Makefiles" -DCMAKE_C_FLAGS=-fPIC -DCMAKE_BUILD_TYPE=Release ..
