### ISSUE TITLE
Telemetry too slow

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/hashlink#151]
When starting NG with hxtelemetry, it takes way too much time to send the data over network, so something must be going wrong in memory tracking somewhere in HL or HxTelemetry code.

**Comment by ncannasse** [comment]
With latest hxtelemetry update it's working but still slow. not sure if it's a limit on the NG client or because the telemetry server is too slow to consume the data. I have to check CPU usage to confirm.

**Comment by jcward** [comment]
One thought, so you can take hxScout out of the loop to decide if the problem is on the sender's side, by simply dumping the packaets to `/dev/null` (should work on osx or linux):

`nc -l 0.0.0.0 7934 > /dev/null`

Or to a file you can open later in hxScout:

`nc -l 0.0.0.0 7934 > session.hxt`

I recall having problems on hxcpp where it was tracking simple allocations (Ints, Floats, etc) -- I may have put in some filters to ignore some things... I'll look around.
