### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/hashlink#159]
Sorry to use Github issues as a way of asking questions. Please let me know if I should use a different forum.

 1. Using HL methods (such as `hl_to_utf8`) creates a dependency on the "libhl" shared library. We'd like to make universal NDLL/HDLL files that work in Neko, HXCPP and HL. How could we make this dependency optional, or runtime only?

 2. We currently have some code to resize a Haxe `Bytes` object in native code doing the following (for HL):

```cpp
unsigned char* data = (unsigned char*)malloc (newSize);
memcpy (bytes->b, data, oldSize);
free (bytes->b);
bytes->b = data;
bytes->length = newSize;
```

...is this reasonable, or would garbage collection (or other problems) occur by doing this?

 3. How would it be possible to create a Haxe `String` from native code? The issue appears to be that we don't have an `hl_type` for `String` hard-coded. This would be really nice for API consistency. I'm afraid to do an `initialize ("")` step (to go and extract the `hl_type*` value at runtime) because of timing. We use static initializers in some places, and initializing something like being able to return a `String` might not occur soon enough.

 4. Do we have to worry about garbage collection? HXCPP has `gc_enter_blocking` and `gc_exit_blocking` calls around any blocking code, because the garbage collector may run from any thread, and may be liable to clobber your objects while you are still using CFFI. This is a little scary and changes something simple like:

```cpp
return Image::LoadFromFile (&bytes->b);
```

into

```cpp
PleaseDontGarbageCollect (&bytes);
GCEnterBlocking ();

ImageData* data = Image::LoadFromFile (&bytes->b);

GCExitBlocking ();
AllowGarbageCollection (&bytes);

// Will ImageData be garbage collected before we return?

return data;
```

 6. Is there a recommended way to determine (at runtime) if our HDLL is being loaded from HL, rather than Neko or HXCPP? Something cheap and easy?

Thank you for your help :smile:

EDIT: One more

 7. How do you convert between `Array<T>` and `hl.NativeArray<T>`, or (conversely) how do you use `Array<T>` on the CFFI side? `varray*` is an `hl.NativeArray<T>`, right?

**Comment by ncannasse** [comment]
1. This is hard to acheive, because for instance Neko functions take "value" as parameter whereas HL takes C int/float/double/void* as parameters, so at best you need to redefine a cross platform API and have different compilation phases for each target.

2. You can use C generated pointers (including malloc'ated ones) as `hl.Bytes` without a problem. However this memory will not be free when haxe.io.Bytes are GC'ed. So if you malloc memory by hand you are responsible to free() it later.

3. Right, you need to return an object with the fields (hl_type*t,void* bytes,int length). Try having a static initializer that passes an empty String to store the String type in a static var before performing such initialization. I might provide an API for hl_resolve_type(const char *name) later.

4. If you want to use multiple threads, you can use `hl_blocking(true); .... hl_blocking(false);` You should not perform any allocation between the two. This is more an optimization that prevents other threads from waiting for your blocking operation in case they want to perform a GC collection.

5. (example) All threads C stacks and registers are scanned so there is no risk for `bytes` to be GC'ed in that case.

6. Not that I know of. But as I mentionned in (1) you might need different builds anyway.

7. `varray*` is a native array of "Objects". Arrays of int/float/etc. are `vbyte*` and are implemented in different classes, so I would advise against passing Haxe Arrays to native code.
