### ISSUE TITLE
Unclear how to use hl_alloc_dynobj

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/hashlink#161]
I think I understand better, now, the relationship between HL `dynamic`, `dynobj` or `virtual`, but I still haven't successfully created an anonymous object in C, and passed it back to Haxe in a way that it will be registered with garbage collection.

Based on the exposed API, I presume the process would be:

 1.) Use `hl_gc_alloc` to allocate memory for garbage collection
 2.) Use `hl_alloc_dynobj` (and stuff it in the GC alloc somehow?)
 3.) Wrap the `vdynobj` with `hl_alloc_dynamic` (`dyn->v.ptr = dynobj`)
 4.) Use `hl_dyn_seti` (etc) to set dynamic fields

However, I assume that `hl_dyn_seti` is not meant to create a new field, but to set one through the `vdynamic` interface, so I don't actually see where new fields could be allocated to a `vdynobj`

In essence, how do you replace `alloc_empty_object` and `alloc_field` calls for HL

**Comment by ncannasse** [comment]
You shouldn't try to wrap your dynobj as virtuals on the C side, instead let the Haxe compiler do that for you. That means that your C binding on Haxe side should return `Dynamic` instead of `{field:Int...}`. If you still want to be able to have structures on Haxe side, you can use the following:

```haxe
abstract Dyn<T>(Dynamic) from T to T {
}
...
typedef Point = { x : Int, y : Int };
@:hlNative("openfl","fun") static function getPos() : Dyn<Point> { return null; }
```

OTOH if you want to return multiple values using the HL way, you can use hl.Ref for that:

```haxe
typedef Point = { x : Int, y : Int };
...
public static function getPos() {  var x = 0, y = 0; _getPos(x,y); return { x : x, y : y }; }
@:hlNative("openfl","fun") static function _getPos( x : hl.Ref<Int>, y : hl.Ref<Int> ) : Void {}
```

On C side, these will be `int *` parameters.
