### ISSUE TITLE
64 bits ptr hash and collision

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/hashlink#217]
In 64 bits, there might be some clashing between finding a free page range in process space and making sure we don't allocate some ptr which hashing will be clashing.

**Comment by luboslenco** [comment]
@ncannasse https://github.com/HaxeFoundation/hashlink/commit/da321acef52cc92cd41c22ff8e3987a71a114478 causes a crash for me on Android at startup. If I revert that commit it 'appears' to run ok. I also tested on Windows and the issue is not present there. If I can provide more details just let me know.

(Running Haxe 4.0.0-rc.1 and HashLink 1.9 in Kha/Armory)

**Comment by ncannasse** [comment]
I'm curious why this occurs. could you list which base_addr values are returned/checked when running on Android?

**Comment by luboslenco** [comment]
Yeah - here is what I get:
```
2019-02-09 10:30:31.409 7508-7546/org.armory3d.arm W/kore: base_addr: 0x71831e0000
2019-02-09 10:30:31.409 7508-7546/org.armory3d.arm W/kore: base_addr: 0x71831d0000
2019-02-09 10:30:31.409 7508-7546/org.armory3d.arm W/kore: base_addr: 0x71831e0000
// crash
```

**Comment by ncannasse** [comment]
@luboslenco could you check with latest GIT ? I think #232 might have fixed your issue

**Comment by luboslenco** [comment]
Awesome - updated to https://github.com/HaxeFoundation/hashlink/commit/349ee6e25231246a9446bd4d71e8919ed1c49dba and it works now, thanks!
