### ISSUE TITLE
src\module.c(274) : FATAL ERROR : Failed to load function std@sys_locale

### ISSUE THREAD

**Issue by tobias1012** [HaxeFoundation/hashlink#233]
Haxe version 3.4.7
HL version 1.1.0

**Comment by Gama11** [comment]
HL 1.1.0 is somewhat ancient by this point, you might wanna try with current versions (HL 1.9 and Haxe 4.0.0-rc.1).

**Comment by ncannasse** [comment]
HL 1.1 should be compatible with 3.4.0, not sure about 3.4.7
But yes as @Gama11 said there was a lot of work done on HL since 1.1, you should upgrade if you want to give it a try.

**Comment by tobias1012** [comment]
Cant use 4.0.0 because of some extensions, 3.4.7 is the latest stable release

**Comment by Magnesus** [comment]
Still getting this error in newest HAXE and HL 1.12.0 when trying to release to Linux... Whole error is: "src/module.c(497) : FATAL ERROR : Failed to load function sdl@warp_mouse_in_window"

I can't check on 1.13 because there is no binary release for Linux, only for Windows, which limits hashlink a lot.
