### ISSUE TITLE
[libuv] libuv cost lot's of cpu.

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hashlink#404]
libuv cost lot's of cpu.

why libuv cost lot's of cpu.

just an instance of tcp.

	class Main {
		static function main() {
		

			var loop = hl.uv.Loop.getDefault();
		
			var tcp = new hl.uv.Tcp(loop);//cost more than 50%~90% of single cpu
		}
	}

![image](https://user-images.githubusercontent.com/748320/89092919-5c24a400-d3e8-11ea-8185-ad71f06343c0.png)

hl    1.12.0

**Comment by sonygod** [comment]
@ncannasse  will you take a look?

**Comment by ncannasse** [comment]
I think this is by design, and definitely not HashLink related.

**Comment by RealyUniqueName** [comment]
I think this happens because of the integration of libuv's default loop into Haxe's MainLoop:
```haxe
loopEvent = haxe.MainLoop.add(function() {
	// if no more things to process, stop
	if (def.run(NoWait) == 0) {
		loopEvent.stop();
		loopEvent = null;
	}
});
```
https://github.com/HaxeFoundation/haxe/blob/fe23a92264be3853dddb03cf664595f2a07aa196/std/hl/uv/Loop.hx#L49-L55
Since tcp handler is alive, `def.run(NoWait)` immediately returns non-zero value. And then MainLoop immediately runs the next tick because `loopEvent` is not stopped.
These PRs should address the issue: https://github.com/HaxeFoundation/hashlink/pull/464, https://github.com/HaxeFoundation/haxe/pull/10342
