### ISSUE TITLE
Multithreading support

### ISSUE THREAD

**Issue by Yanrishatum** [HaxeFoundation/hashlink#42]
I see some works were done on a threading side, but I'm not sure how it would work considering of GC notification if exposed to Haxe API right now.  
So, what plans on a multithreading support, and how may I help with it? Considering I have no idea how HL GC works or how to implement it to support several threads.  
Small UPD: I've made some supporting classes (`Lock`, `Mutex`, and `Deque`, but I'm seriously not sure if they are done properly, plus windows only) copying implementation from NekoVM in my [fork](https://github.com/Yanrishatum/hashlink/)

**Comment by ncannasse** [comment]
This requires the following steps:
- add a global lock for gc_alloc_gen, to prevent two threads from allocating
- keep a list of threads running, each with their own stack top
- when we want to start a collection, we need to wait until all threads are stopped. a thread can be stopped when trying to do an allocation or when leaving a blocking section
- blocking sections can be added in some native system primitives which does not perform allocation but might lock the thread for some time. This allow the GC not to wait for such a blocked thread. sys_sleep, socket and file i/o are good candidates.
- once all threads are stopped, we need to scan all their stacks + gc roots. A good optimization here is to use as many threads for that as we have CPU cores
- there is some additional work to have stack traces per-thread since currently stack top is a static in JIT/HLC

**Comment by ncannasse** [comment]
In progress here https://github.com/HaxeFoundation/hashlink/tree/threads

Note for threading implementation (things to deal with)
- error.c: stack_trace/stack_count/exc_rethrow (TLS)
- obj.c: hl_cache (lock)
- gc.c: lock in gc_alloc_gen
- gc.c: is_blocking (TLS) + hl_is_blocking should get hl_thread param ?
- check libs for statics

**Comment by ncannasse** [comment]
I haven't merged the branch yet because of the following benchmark.

```haxe
class Main {	
   public static function main() {
		var t0 = Sys.time();
		for( i in 0...10000000 )
			new hl.Bytes(1);
		trace(Sys.time() - t0);
    }
}
```

- without HL_THREADS: 0.47s
- with HL_THREADS: 1.18s

Time is used by:
- [ ] 0.11s in gc_save_context in global_lock: this could be avoided by waking up the locked threads if a stop the world is necessary.
- [ ] 0.45s in global_lock mutex acquire/release: finding a faster soft lock seems necessary, especially since it's most likely low concurrency
- [ ] 0.15s in TLS thread get : use faster TLS for Windows http://cbloomrants.blogspot.fr/2013/09/09-18-13-fast-tls-on-windows.html

**Comment by ncannasse** [comment]
Progress in #123

**Comment by ncannasse** [comment]
Threads support has been merged.

**Comment by sonygod** [comment]
is possible  use hashlink replace Neko as socket server now? 
@ncannasse

**Comment by ncannasse** [comment]
@sonygod for a generic socket server yes it should be doable. Maybe even more efficient if you use `hl.uv.Tcp` given it uses libuv (no need for threads in that case)

**Comment by sonygod** [comment]
could you build the last hashlink 1.6? binary for download?
it's seem haxe last build  do not support hashlink1.5,

**Comment by ncannasse** [comment]
Yes I am planning to release 1.6 soon

**Comment by sonygod** [comment]
could you give some small example how to use hl.uv.tcp libuv?
BTW,what's the mean uv in hl.uv?
current I want to use hashlink1.6 repalce neko 2.1,

**Comment by ncannasse** [comment]
@sonygod you can update to Haxe 4.0-preview 4 and HL 1.6 now. "uv" is about "libuv" (https://github.com/libuv/libuv) you can read their manual and use hl.uv package as part of Haxe std library

**Comment by flashultra** [comment]
@ncannasse  I'm working on generic socket server (using Hashlink and sys.net.* )  and looking to create three separate threads for acceptor, socket reader and socket writer from the main class.
 In java I just can implements Runnable to create thread from class.
   How I can create / start thread in Hashlink ?

**Comment by ncannasse** [comment]
@flashultra use   `hl.vm.Thread.create(function() { .... })`

**Comment by flashultra** [comment]
@ncannasse  Something goes wrong with Thread.create . I did this for test :
```haxe
      Thread.create(function() {
           while(true) {
               trace("test");
           }
        });
```
and after 6 iteration thread stops . The final result was : 
```
src/Server.hx:52: test  
src/Server.hx:52: test  
src/Server.hx:52: test  
src/Server.hx:52: test  
src/Server.hx:52: test  
src/Server.hx:52: test  
src/Serve  
PS   
```
I'm using HL/JIT 1.6.0  and Haxe 4.0.0-preview.4+1e3e5e016

**Comment by ncannasse** [comment]
If the main thread exit the application will stop.

**Comment by flashultra** [comment]
@ncannasse  Thank you for you help. Would I ask what is the best way to share Array<Socket> between two threads ?  At the moment I've got strange error , but when not used threads everything works:
```
Uncaught exception: Error while waiting on socket
Called from sys.net.$Socket.select(C:\HaxeToolkit\haxe\std/hl/_std/sys/net/Socket.hx:245)
```
In details:
  I have two classes SocketAcceptor  and SocketReader running in separate threads . In SocketAcceptor  I bind to server ip and port . Here is part of the code , where   ``connections : Array<Socket>``
```haxe
              var select  = Socket.select([server], null, null, 0);
                for (socket in select.read)
		{
                    var client : Socket = socket.accept();
                    client.setBlocking(false);
                    connections.push(client);
                }
```
In SocketReader i have:
```haxe
if ( socketAcceptor.connections.length > 0 ) 
            {
                var select  = Socket.select(socketAcceptor.connections, null, null,0);
                for (socket in select.read)
                {
                    try
                    {
                        bytesReceived = socket.input.readBytes(buffer, 0, buffer.length);
                        trace(bytesReceived+" , "+buffer);
                    }  catch (e:Eof) {
                        socket.close();
                        socketAcceptor.connections.remove(socket);
                    }
                }
            }
```
but everything stops after Socket.select(socketAcceptor.connections, ..... ) and return the error above
Same code when it is in one thread works. In java I can use synchronize(...) , but I'm not sure is it necessary to use some synchronization here ?
 Thank you again for your time.

**Comment by ncannasse** [comment]
@flashultra you can use hl.vm.Mutex to ensure two threads don't modify the array at the same time
