### ISSUE TITLE
Having trouble running my game with HashLink when using a third party C/C++ DLL

### ISSUE THREAD

**Issue by Tanz0rz** [HaxeFoundation/hashlink#428]
My game integrates with a third party DLL written in C/C++. I get very strange results with HashLink builds (both bad behavior and crashes).

Version information:
Haxe: 4.1.4
HashLink: 1.10
openfl: 9.0.2
lime: 7.8.0

The most common error I am hitting is this one which crashes the game:
```
src\alloc.c(211) : FATAL ERROR : Can't lock GC in unregistered thread
```

The game works fine for `windows` and `html` targets. `hashlink` has been uniquely problematic and I have narrowed it down to an issue that happens when HashLink interacts with the third party DLL (an external audio engine).

Here is the source code for the HaxeFlixel game (there is an `init.sh` script in there to install all the non-flixel dependencies and `lime test hl` is the build command): https://github.com/bitDecayGames/GithubGameOff2020

Here is the source for the library that talks to the third party C/C++ DLL's (you will want to be on the branch `hl-v2-modifications-v2` to get the HashLink-converted version of the library): https://github.com/Tanz0rz/haxe-fmod

I have spent _a lot_ of effort trying to get this all working with HashLink. If you end up setting this up locally, let me know and I will help however I can.

This whole effort has got me wondering if the HashLink runtime supports interactions with the traditional C/C++ code of the third party DLL I am using.

**Comment by ncannasse** [comment]
Hi !
Seems like the issue is that some library is creating a thread and doing some callbacks to Haxe or Hashlink/C code that does some allocation. You either need to register this thread for garbage collection (using hl_register_thread/hl_unregister_thread) but it's not easy if you don't control the thread loop.
Another solution it to make sure all events from the thread(s) are saved into some data structure in C (or in Haxe but with 0 allocation) and then processed by the main thread.

**Comment by Tanz0rz** [comment]
I think the second solution will be what I try. Thank you.
