### ISSUE TITLE
Program never completed

### ISSUE THREAD

**Issue by eliasku** [HaxeFoundation/hashlink#9]
I tried to run tests for `hxease`, and running with `hl test/test.hl` starts and never completes with 100% cpu usage.

I use OSX 10.11.5.
`haxe` nightly  from 20 oct 2016
`hl` builded for osx with `make` from git at 20 oct 2016 (as how it's done on hl travis-ci script)
hxease: https://github.com/eliasku/hxease/tree/develop

Builded tests which is never completes: [test.hl.zip](https://github.com/HaxeFoundation/hl/files/543636/test.hl.zip)

**Comment by ncannasse** [comment]
What is the source code for the example?

**Comment by ncannasse** [comment]
(or can it be reproduced with a smaller pure Haxe code sample without any lib?)

**Comment by eliasku** [comment]
@ncannasse I will try to pack repro in 30 minutes for you

**Comment by eliasku** [comment]
[hl-repro.zip](https://github.com/HaxeFoundation/hl/files/545273/hl-repro.zip)
There are `hl.hxml` and `neko.hxml`

**Comment by haxiomic** [comment]
The repro is also hanging on my mac running 10.11.6

I'm having the same issue running the mandlebrot test, it gets to pixel (214,1) and hangs in both hl JIT and compiled HLC

**Comment by ncannasse** [comment]
I can't reproduce on Windows, I'll have to check on OSX at work this week.

**Comment by haxiomic** [comment]
I've made a PR for the fix and the hl-repro project no longer hangs

It turned out to be the TRAILING_ZEROES macro. On windows it's defined as an inline function whereas on other platforms it's the macro:
```c
#define TRAILING_ZEROES(x)	(x?__builtin_ctz(x):32)
```

The problem is if x is a ternary expression like `a ? b : c` then if a is true TRAILING_ZEROES will return a rather than __builtin_ctz(a).

I've changed the macros to inline functions which also prevents x being evaluated twice.

The hang itself occurred in gc_alloc_var - [alloc.c:383](https://github.com/HaxeFoundation/hl/blob/master/src/alloc.c#L383) bits gets set incorrectly because of the ternary
